# Generated by Django 5.2 on 2025-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MigrationTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_int", models.IntegerField()),
                ("field_int_unique", models.IntegerField(unique=True)),
                ("field_int_not_indexed", models.IntegerField()),
                ("field_int_not_null", models.IntegerField()),
                ("field_int_null", models.IntegerField(null=True)),
                ("field_int_default", models.IntegerField(default=54321)),
                ("field_float", models.FloatField()),
                ("field_char", models.CharField(max_length=100)),
                ("field_bool", models.BooleanField()),
                ("field_date", models.DateField()),
                ("field_datetime", models.DateTimeField()),
                ("field_json", models.JSONField(default=dict)),
                ("field_uuid", models.UUIDField()),
            ],
        ),
    ]
